#pragma once

#define IMNX_DEFAULT_WIDTH  1280
#define IMNX_DEFAULT_HEIGHT 720

#define IMNX_TOUCH_SPACE_WIDTH  1280.0f
#define IMNX_TOUCH_SPACE_HEIGHT 720.0f

#define IMNX_CMD_SLICES          8
#define IMNX_CMD_SLICE_SIZE      0x8000
#define IMNX_CONTROL_SLICE_SIZE  0x2000

#define IMNX_CMD_MEMORY_SIZE     (IMNX_CMD_SLICES * IMNX_CMD_SLICE_SIZE)
#define IMNX_CONTROL_MEMORY_SIZE (IMNX_CMD_SLICES * IMNX_CONTROL_SLICE_SIZE)

#define IMNX_INIT_TOUCHSCREEN 1

#define IMNX_UI_SCALE      2.0f
#define IMNX_MIN_TOUCH_PAD 8.0f
